CREATE TABLE `test`.`users` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `login` VARCHAR(20) NOT NULL,
    `password` TEXT NOT NULL,
    `description` TEXT NULL,
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `modified` TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY

    